In [10]:
#Importar la funcion CSV para tratamiento de archivos:
import csv
#Importar OS para leer directorio actual
import os

#Obtener el directorio actual
cwd=os.getcwd()

#Imprimir directorio
print(cwd)

#Abrir archivo de lectura:
with open('Height of Male and Female by Country 2022.csv','r', encoding='utf-8') as csvfile:
    
    #Lee el archivo en el objeto csvreader
    csvreader=csv.reader(csvfile)
    
#Imprimir primeras 50 lineas
    rows=[]
    for row in csvreader:
        rows.append(row)
    print(rows[:50])

c:\Users\ACamacho\Desktop\EBAC\MOD12
[['Rank', 'Country Name', 'Male Height in Cm', 'Female Height in Cm', 'Male Height in Ft', 'Female Height in Ft'], ['1', 'Netherlands', '183.78', '170.36', '6.03', '5.59'], ['2', 'Montenegro', '183.30', '169.96', '6.01', '5.58'], ['3', 'Estonia', '182.79', '168.66', '6.00', '5.53'], ['4', 'Bosnia and Herzegovina', '182.47', '167.47', '5.99', '5.49'], ['5', 'Iceland', '182.10', '168.91', '5.97', '5.54'], ['6', 'Denmark', '181.89', '169.47', '5.97', '5.56'], ['7', 'Czech Republic', '181.19', '167.96', '5.94', '5.51'], ['8', 'Latvia', '181.17', '168.81', '5.94', '5.54'], ['9', 'Slovakia', '181.02', '167.12', '5.94', '5.48'], ['10', 'Slovenia', '180.98', '167.20', '5.94', '5.49'], ['11', 'Ukraine', '180.98', '166.62', '5.94', '5.47'], ['12', 'Croatia', '180.76', '166.80', '5.93', '5.47'], ['13', 'Serbia', '180.74', '168.29', '5.93', '5.52'], ['14', 'Lithuania', '180.72', '167.63', '5.93', '5.50'], ['15', 'Poland', '180.69', '165.78', '5.93', '5.44'], ['16', 'Finland', '180.57', '166.48', '5.92', '5.46'], ['17', 'Norway', '180.48', '166.45', '5.92', '5.46'], ['18', 'Sweden', '180.46', '166.67', '5.92', '5.47'], ['19', 'Germany', '180.28', '166.18', '5.91', '5.45'], ['20', 'Dominica', '180.15', '166.89', '5.91', '5.48'], ['21', 'Bermuda', '179.72', '166.11', '5.90', '5.45'], ['22', 'Puerto Rico', '179.48', '163.06', '5.89', '5.35'], ['23', 'Greece', '179.26', '165.81', '5.88', '5.44'], ['24', 'Belgium', '179.09', '163.40', '5.88', '5.36'], ['25', 'Ireland', '179.04', '164.50', '5.87', '5.40'], ['26', 'Lebanon', '178.96', '163.67', '5.87', '5.37'], ['27', 'Andorra', '178.84', '165.53', '5.87', '5.43'], ['28', 'Antigua and Barbuda', '178.84', '165.72', '5.87', '5.44'], ['29', 'Australia', '178.77', '164.67', '5.87', '5.40'], ['30', 'Canada', '178.75', '164.73', '5.86', '5.40'], ['31', 'Switzerland', '178.73', '164.33', '5.86', '5.39'], ['32', 'Grenada', '178.70', '165.99', '5.86', '5.45'], ['33', 'Belarus', '178.69', '166.93', '5.86', '5.48'], ['34', 'France', '178.60', '164.49', '5.86', '5.40'], ['35', 'Austria', '178.52', '166.93', '5.86', '5.48'], ['36', 'Luxembourg', '178.46', '165.07', '5.86', '5.42'], ['37', 'Cook Islands', '178.32', '167.31', '5.85', '5.49'], ['38', 'French Polynesia', '178.32', '166.52', '5.85', '5.46'], ['39', 'United Kingdom', '178.21', '163.94', '5.85', '5.38'], ['40', 'Romania', '177.82', '164.73', '5.83', '5.40'], ['41', 'New Zealand', '177.72', '164.66', '5.83', '5.40'], ['42', 'Saint Vincent and the Grenadines', '177.49', '165.30', '5.82', '5.42'], ['43', 'Niue', '177.19', '167.03', '5.81', '5.48'], ['44', 'American Samoa', '177.09', '167.55', '5.81', '5.50'], ['45', 'Barbados', '177.03', '165.66', '5.81', '5.44'], ['46', 'Jamaica', '176.97', '164.32', '5.81', '5.39'], ['47', 'United States', '176.94', '163.31', '5.81', '5.36'], ['48', 'Tunisia', '176.85', '161.69', '5.80', '5.30'], ['49', 'Russia', '176.65', '164.52', '5.80', '5.40']]

In [21]:
#Imprimir todas las lineas
with open('Height of Male and Female by Country 2022.csv', 'r', encoding='utf-8') as csvfile:
    # Crear un lector CSV
    csvreader = csv.reader(csvfile)
    
    
    # Crear una lista para almacenar todas las líneas
    rows = []
    
    # Leer todas las líneas y agregarlas a la lista 'rows'
    for row in csvreader:
        rows.append(row)
    
# Imprimir todas las líneas
for row in rows:
    print(row)

['Rank', 'Country Name', 'Male Height in Cm', 'Female Height in Cm', 'Male Height in Ft', 'Female Height in Ft']
['1', 'Netherlands', '183.78', '170.36', '6.03', '5.59']
['2', 'Montenegro', '183.30', '169.96', '6.01', '5.58']
['3', 'Estonia', '182.79', '168.66', '6.00', '5.53']
['4', 'Bosnia and Herzegovina', '182.47', '167.47', '5.99', '5.49']
['5', 'Iceland', '182.10', '168.91', '5.97', '5.54']
['6', 'Denmark', '181.89', '169.47', '5.97', '5.56']
['7', 'Czech Republic', '181.19', '167.96', '5.94', '5.51']
['8', 'Latvia', '181.17', '168.81', '5.94', '5.54']
['9', 'Slovakia', '181.02', '167.12', '5.94', '5.48']
['10', 'Slovenia', '180.98', '167.20', '5.94', '5.49']
['11', 'Ukraine', '180.98', '166.62', '5.94', '5.47']
['12', 'Croatia', '180.76', '166.80', '5.93', '5.47']
['13', 'Serbia', '180.74', '168.29', '5.93', '5.52']
['14', 'Lithuania', '180.72', '167.63', '5.93', '5.50']
['15', 'Poland', '180.69', '165.78', '5.93', '5.44']
['16', 'Finland', '180.57', '166.48', '5.92', '5.46']
['17', 'Norway', '180.48', '166.45', '5.92', '5.46']
['18', 'Sweden', '180.46', '166.67', '5.92', '5.47']
['19', 'Germany', '180.28', '166.18', '5.91', '5.45']
['20', 'Dominica', '180.15', '166.89', '5.91', '5.48']
['21', 'Bermuda', '179.72', '166.11', '5.90', '5.45']
['22', 'Puerto Rico', '179.48', '163.06', '5.89', '5.35']
['23', 'Greece', '179.26', '165.81', '5.88', '5.44']
['24', 'Belgium', '179.09', '163.40', '5.88', '5.36']
['25', 'Ireland', '179.04', '164.50', '5.87', '5.40']
['26', 'Lebanon', '178.96', '163.67', '5.87', '5.37']
['27', 'Andorra', '178.84', '165.53', '5.87', '5.43']
['28', 'Antigua and Barbuda', '178.84', '165.72', '5.87', '5.44']
['29', 'Australia', '178.77', '164.67', '5.87', '5.40']
['30', 'Canada', '178.75', '164.73', '5.86', '5.40']
['31', 'Switzerland', '178.73', '164.33', '5.86', '5.39']
['32', 'Grenada', '178.70', '165.99', '5.86', '5.45']
['33', 'Belarus', '178.69', '166.93', '5.86', '5.48']
['34', 'France', '178.60', '164.49', '5.86', '5.40']
['35', 'Austria', '178.52', '166.93', '5.86', '5.48']
['36', 'Luxembourg', '178.46', '165.07', '5.86', '5.42']
['37', 'Cook Islands', '178.32', '167.31', '5.85', '5.49']
['38', 'French Polynesia', '178.32', '166.52', '5.85', '5.46']
['39', 'United Kingdom', '178.21', '163.94', '5.85', '5.38']
['40', 'Romania', '177.82', '164.73', '5.83', '5.40']
['41', 'New Zealand', '177.72', '164.66', '5.83', '5.40']
['42', 'Saint Vincent and the Grenadines', '177.49', '165.30', '5.82', '5.42']
['43', 'Niue', '177.19', '167.03', '5.81', '5.48']
['44', 'American Samoa', '177.09', '167.55', '5.81', '5.50']
['45', 'Barbados', '177.03', '165.66', '5.81', '5.44']
['46', 'Jamaica', '176.97', '164.32', '5.81', '5.39']
['47', 'United States', '176.94', '163.31', '5.81', '5.36']
['48', 'Tunisia', '176.85', '161.69', '5.80', '5.30']
['49', 'Russia', '176.65', '164.52', '5.80', '5.40']
['50', 'Hungary', '176.59', '162.55', '5.79', '5.33']
['51', 'Saint Lucia', '176.43', '165.52', '5.79', '5.43']
['52', 'North Macedonia', '176.43', '160.88', '5.79', '5.28']
['53', 'Libya', '176.39', '162.56', '5.79', '5.33']
['54', 'Turkey', '176.36', '161.80', '5.79', '5.31']
['55', 'Morocco', '176.35', '161.18', '5.79', '5.29']
['56', 'Senegal', '176.18', '163.92', '5.78', '5.38']
['57', 'Spain', '176.11', '162.03', '5.78', '5.32']
['58', 'Tokelau', '176.06', '166.08', '5.78', '5.45']
['59', 'Trinidad and Tobago', '176.03', '163.38', '5.78', '5.36']
['60', 'Israel', '175.98', '162.22', '5.77', '5.32']
['61', 'Georgia', '175.98', '163.24', '5.77', '5.36']
['62', 'Seychelles', '175.90', '162.47', '5.77', '5.33']
['63', 'Brazil', '175.73', '162.41', '5.77', '5.33']
['64', 'China', '175.66', '163.46', '5.76', '5.36']
['65', 'Iran', '175.62', '161.18', '5.76', '5.29']
['66', 'Moldova', '175.59', '162.96', '5.76', '5.35']
['67', 'South Korea', '175.52', '163.23', '5.76', '5.36']
['68', 'Kazakhstan', '175.50', '161.74', '5.76', '5.31']
['69', 'Tonga', '175.11', '166.08', '5.75', '5.45']
['70', 'Palestine', '175.05', '161.28', '5.74', '5.29']
['71', 'Algeria', '175.04', '162.35', '5.74', '5.33']
['72', 'Mali', '175.02', '161.99', '5.74', '5.31']
['73', 'Kuwait', '174.96', '160.10', '5.74', '5.25']
['74', 'Jordan', '174.84', '159.46', '5.74', '5.23']
['75', 'Hong Kong', '174.83', '160.62', '5.74', '5.27']
['76', 'Argentina', '174.76', '161.22', '5.73', '5.29']
['77', 'North Korea', '174.69', '161.22', '5.73', '5.29']
['78', 'Dominican Republic', '174.65', '161.21', '5.73', '5.29']
['79', 'Egypt', '174.57', '160.88', '5.73', '5.28']
['80', 'Suriname', '174.51', '162.26', '5.73', '5.32']
['81', 'Italy', '174.42', '161.81', '5.72', '5.31']
['82', 'Samoa', '174.42', '163.82', '5.72', '5.37']
['83', 'Bahamas', '174.40', '163.46', '5.72', '5.36']
['84', 'Malta', '174.38', '162.95', '5.72', '5.35']
['85', 'Turkmenistan', '174.37', '162.83', '5.72', '5.34']
['86', 'Portugal', '174.37', '161.23', '5.72', '5.29']
['87', 'Uruguay', '174.32', '161.56', '5.72', '5.30']
['88', 'Bulgaria', '174.17', '164.58', '5.71', '5.40']
['89', 'United Arab Emirates', '174.08', '160.53', '5.71', '5.27']
['90', 'Albania', '174.07', '162.23', '5.71', '5.32']
['91', 'Costa Rica', '174.04', '160.36', '5.71', '5.26']
['92', 'Azerbaijan', '174.00', '161.37', '5.71', '5.29']
['93', 'Fiji', '173.98', '164.28', '5.71', '5.39']
['94', 'Greenland', '173.84', '161.40', '5.70', '5.30']
['95', 'Paraguay', '173.81', '159.76', '5.70', '5.24']
['96', 'Iraq', '173.79', '158.75', '5.70', '5.21']
['97', 'Saint Kitts and Nevis', '173.71', '162.78', '5.70', '5.34']
['98', 'Armenia', '173.67', '159.85', '5.70', '5.24']
['99', 'Cuba', '173.56', '160.13', '5.69', '5.25']
['100', 'Venezuela', '173.53', '160.04', '5.69', '5.25']
['101', 'Taiwan', '173.53', '160.70', '5.69', '5.27']
['102', 'Singapore', '173.50', '161.30', '5.69', '5.29']
['103', 'Qatar', '173.27', '160.72', '5.68', '5.27']
['104', 'Botswana', '173.16', '162.06', '5.68', '5.32']
['105', 'Mauritius', '173.01', '158.94', '5.68', '5.21']
['106', 'Chile', '172.88', '159.42', '5.67', '5.23']
['107', 'Bahrain', '172.76', '158.29', '5.67', '5.19']
['108', 'Cyprus', '172.75', '160.55', '5.67', '5.27']
['109', 'Haiti', '172.23', '160.58', '5.65', '5.27']
['110', 'Guyana', '172.15', '159.57', '5.65', '5.24']
['111', 'Cameroon', '172.13', '160.41', '5.65', '5.26']
['112', 'Sudan', '172.07', '160.36', '5.65', '5.26']
['113', 'Japan', '172.06', '158.50', '5.65', '5.20']
['114', 'Burkina Faso', '171.89', '161.33', '5.64', '5.29']
['115', 'Colombia', '171.85', '157.96', '5.64', '5.18']
['116', 'Chad', '171.84', '162.12', '5.64', '5.32']
['117', 'Oman', '171.70', '158.44', '5.63', '5.20']
['118', 'Kyrgyzstan', '171.66', '160.20', '5.63', '5.26']
['119', 'Syria', '171.64', '159.38', '5.63', '5.23']
['120', 'Thailand', '171.61', '159.42', '5.63', '5.23']
['121', 'Nigeria', '171.55', '158.14', '5.63', '5.19']
['122', 'Tuvalu', '171.30', '163.57', '5.62', '5.37']
['123', 'Republic of the Congo', '171.23', '158.78', '5.62', '5.21']
['124', 'Somalia', '171.22', '159.86', '5.62', '5.24']
['125', 'Uzbekistan', '170.94', '160.29', '5.61', '5.26']
['126', 'Djibouti', '170.77', '159.82', '5.60', '5.24']
['127', 'Guinea', '170.70', '158.75', '5.60', '5.21']
['128', 'Zimbabwe', '170.69', '159.85', '5.60', '5.24']
['129', 'Mongolia', '170.67', '159.89', '5.60', '5.25']
['130', 'El Salvador', '170.67', '156.39', '5.60', '5.13']
['131', 'Saudi Arabia', '170.67', '158.84', '5.60', '5.21']
['132', 'Palau', '170.62', '159.52', '5.60', '5.23']
['133', 'Eritrea', '170.60', '157.58', '5.60', '5.17']
['134', 'Belize', '170.52', '158.12', '5.59', '5.19']
['135', 'Gabon', '170.48', '160.05', '5.59', '5.25']
['136', 'Kenya', '170.46', '159.43', '5.59', '5.23']
['137', 'Sao Tome and Principe', '170.37', '159.81', '5.59', '5.24']
['138', 'Ghana', '170.30', '158.86', '5.59', '5.21']
['139', 'Mexico', '170.29', '157.90', '5.59', '5.18']
['140', 'Niger', '170.26', '159.81', '5.59', '5.24']
['141', 'Panama', '170.19', '158.19', '5.58', '5.19']
['142', 'Togo', '170.14', '159.13', '5.58', '5.22']
['143', 'Kiribati', '170.09', '161.04', '5.58', '5.28']
['144', 'Nicaragua', '169.91', '155.62', '5.57', '5.11']
['145', 'Namibia', '169.75', '160.26', '5.57', '5.26']
['146', 'South Africa', '169.63', '158.58', '5.57', '5.20']
['147', 'Honduras', '169.59', '155.18', '5.56', '5.09']
['148', 'Micronesia', '169.57', '159.66', '5.56', '5.24']
['149', 'Nauru', '169.57', '157.82', '5.56', '5.18']
['150', 'Eswatini', '169.41', '158.92', '5.56', '5.21']
['151', 'Malaysia', '169.20', '157.06', '5.55', '5.15']
['152', 'Central African Republic', '169.01', '159.65', '5.54', '5.24']
['153', 'Vietnam', '168.89', '158.43', '5.54', '5.20']
['154', 'Ethiopia', '168.84', '157.15', '5.54', '5.16']
['155', 'Uganda', '168.74', '158.53', '5.54', '5.20']
['156', 'DR Congo', '168.60', '156.30', '5.53', '5.13']
['157', 'Afghanistan', '168.50', '156.11', '5.53', '5.12']
['158', 'Angola', '168.46', '158.10', '5.53', '5.19']
['159', 'Benin', '168.44', '158.40', '5.53', '5.20']
['160', 'Tajikistan', '168.43', '158.12', '5.53', '5.19']
['161', 'Gambia', '168.36', '161.73', '5.52', '5.31']
['162', 'Vanuatu', '168.29', '160.48', '5.52', '5.27']
['163', 'Ivory Coast', '168.23', '158.65', '5.52', '5.21']
['164', 'Equatorial Guinea', '168.18', '158.05', '5.52', '5.19']
['165', 'Guinea-Bissau', '168.17', '158.72', '5.52', '5.21']
['166', 'Bolivia', '168.10', '155.58', '5.52', '5.10']
['167', 'Sri Lanka', '168.07', '155.88', '5.51', '5.11']
['168', 'Lesotho', '167.92', '156.72', '5.51', '5.14']
['169', 'Maldives', '167.87', '154.28', '5.51', '5.06']
['170', 'Comoros', '167.72', '156.54', '5.50', '5.14']
['171', 'Zambia', '167.62', '157.32', '5.50', '5.16']
['172', 'Burundi', '167.34', '155.08', '5.49', '5.09']
['173', 'Pakistan', '167.33', '154.77', '5.49', '5.08']
['174', 'Ecuador', '167.32', '155.25', '5.49', '5.09']
['175', 'Bhutan', '167.05', '155.15', '5.48', '5.09']
['176', 'Tanzania', '166.98', '156.89', '5.48', '5.15']
['177', 'Peru', '166.75', '154.39', '5.47', '5.07']
['178', 'Myanmar', '166.70', '154.71', '5.47', '5.08']
['179', 'India', '166.50', '155.18', '5.46', '5.09']
['180', 'Sierra Leone', '166.43', '157.34', '5.46', '5.16']
['181', 'Brunei', '166.31', '154.90', '5.46', '5.08']
['182', 'Indonesia', '166.26', '154.36', '5.45', '5.06']
['183', 'Rwanda', '166.02', '156.72', '5.45', '5.14']
['184', 'Malawi', '165.68', '156.14', '5.44', '5.12']
['185', 'Mauritania', '165.54', '160.06', '5.43', '5.25']
['186', 'Liberia', '165.48', '156.54', '5.43', '5.14']
['187', 'Cambodia', '165.35', '154.75', '5.42', '5.08']
['188', 'Marshall Islands', '165.26', '154.76', '5.42', '5.08']
['189', 'Philippines', '165.23', '154.14', '5.42', '5.06']
['190', 'Madagascar', '165.16', '153.06', '5.42', '5.02']
['191', 'Bangladesh', '165.08', '152.38', '5.42', '5.00']
['192', 'Yemen', '164.42', '154.76', '5.39', '5.08']
['193', 'Nepal', '164.36', '152.39', '5.39', '5.00']
['194', 'Guatemala', '164.36', '150.91', '5.39', '4.95']
['195', 'Mozambique', '164.30', '155.42', '5.39', '5.10']
['196', 'Papua New Guinea', '163.10', '156.89', '5.35', '5.15']
['197', 'Solomon Islands', '163.07', '156.79', '5.35', '5.14']
['198', 'Laos', '162.78', '153.10', '5.34', '5.02']
['199', 'Timor-Leste', '160.13', '152.71', '5.25', '5.01']

In [28]:
#Calcular la media, mínima y máxima altura de hombres y mujeres del data set completo

#1. importamos modulo numpy

import numpy as np

#2. Generamos en objeto height con todas las filas de la lista:
heights_global=np.array(rows)

#como referencia mostrar la primera linea del array
heights_global[0]

array(['Rank', 'Country Name', 'Male Height in Cm', 'Female Height in Cm',
       'Male Height in Ft', 'Female Height in Ft'], dtype='<U32')

In [31]:
#3. Muestra la columna  de "Male Height in Cm" y"Female Height in Cm"
#Recordar que cuando se usan arrays (numpy) los indices empiezan en cero!
male_heights=heights_global[0:,2]
female_heights=heights_global[0:,3]
male_heights

array(['Male Height in Cm', '183.78', '183.30', '182.79', '182.47',
       '182.10', '181.89', '181.19', '181.17', '181.02', '180.98',
       '180.98', '180.76', '180.74', '180.72', '180.69', '180.57',
       '180.48', '180.46', '180.28', '180.15', '179.72', '179.48',
       '179.26', '179.09', '179.04', '178.96', '178.84', '178.84',
       '178.77', '178.75', '178.73', '178.70', '178.69', '178.60',
       '178.52', '178.46', '178.32', '178.32', '178.21', '177.82',
       '177.72', '177.49', '177.19', '177.09', '177.03', '176.97',
       '176.94', '176.85', '176.65', '176.59', '176.43', '176.43',
       '176.39', '176.36', '176.35', '176.18', '176.11', '176.06',
       '176.03', '175.98', '175.98', '175.90', '175.73', '175.66',
       '175.62', '175.59', '175.52', '175.50', '175.11', '175.05',
       '175.04', '175.02', '174.96', '174.84', '174.83', '174.76',
       '174.69', '174.65', '174.57', '174.51', '174.42', '174.42',
       '174.40', '174.38', '174.37', '174.37', '174.32', '174.17',
       '174.08', '174.07', '174.04', '174.00', '173.98', '173.84',
       '173.81', '173.79', '173.71', '173.67', '173.56', '173.53',
       '173.53', '173.50', '173.27', '173.16', '173.01', '172.88',
       '172.76', '172.75', '172.23', '172.15', '172.13', '172.07',
       '172.06', '171.89', '171.85', '171.84', '171.70', '171.66',
       '171.64', '171.61', '171.55', '171.30', '171.23', '171.22',
       '170.94', '170.77', '170.70', '170.69', '170.67', '170.67',
       '170.67', '170.62', '170.60', '170.52', '170.48', '170.46',
       '170.37', '170.30', '170.29', '170.26', '170.19', '170.14',
       '170.09', '169.91', '169.75', '169.63', '169.59', '169.57',
       '169.57', '169.41', '169.20', '169.01', '168.89', '168.84',
       '168.74', '168.60', '168.50', '168.46', '168.44', '168.43',
       '168.36', '168.29', '168.23', '168.18', '168.17', '168.10',
       '168.07', '167.92', '167.87', '167.72', '167.62', '167.34',
       '167.33', '167.32', '167.05', '166.98', '166.75', '166.70',
       '166.50', '166.43', '166.31', '166.26', '166.02', '165.68',
       '165.54', '165.48', '165.35', '165.26', '165.23', '165.16',
       '165.08', '164.42', '164.36', '164.36', '164.30', '163.10',
       '163.07', '162.78', '160.13'], dtype='<U32')

In [36]:
# Verificación de tipo de datos

male_heights.dtype

dtype('<U32')

In [42]:
#4.Transformacion del array en numeros, ya que U32 significa que estoy tratando con strings

#Vamos a generar un array solamente de las alturas (valores numericos a transformar)
male_ht=male_heights[1:]
female_ht=female_heights[1:]

male_ht_float=[float(numeric_string) for numeric_string in male_ht]
#male_ht[:10] #Comprobacion
female_ht_float=[float(numeric_string) for numeric_string in female_ht]
#female_ht[:10]

array(['170.36', '169.96', '168.66', '167.47', '168.91', '169.47',
       '167.96', '168.81', '167.12', '167.20'], dtype='<U32')

In [52]:


#5. Importando  modulo de Estadística:

from statistics import mean, median, mode, stdev

#6. Calculo de la media, min maxima altura de hombres y mujeres del arreglo:
mean_ht_men=mean(male_ht_float)
min_ht_men=min(male_ht_float)
max_ht_men=max(male_ht_float)

mean_ht_women=mean(female_ht_float)
min_ht_women=min(female_ht_float)
max_ht_women=max(female_ht_float)

#Reporte estadistico de los daton

print(f'En promedio a nivel mundial, la altura para hombres es {mean_ht_men:.2f} cm  y para mujeres es {mean_ht_women:.2f} cm \n') 
print(f'A nivel mundial los mínimos para la altura de hombres es {min_ht_men:.2f} cm  y para mujeres es {min_ht_women:.2f} cm \n')
print(f'A nivel mundial los máximos para la altura de hombres es {max_ht_men:.2f} cm  y para mujeres es {max_ht_women:.2f} cm \n')

En promedio a nivel mundial, la altura para hombres es 173.09 cm  y para mujeres es 160.94 cm

A nivel mundial los mínimos para la altura de hombres es 160.13 cm  y para mujeres es 150.91 cm

A nivel mundial los máximos para la altura de hombres es 183.78 cm  y para mujeres es 170.36 cm

## Obtener la data de mi país de origen: México

In [61]:
#Filtro para el país

filter_Pais=heights_global[:,1] == 'Mexico' #En todos los rows de la columna Country Name (1)
Height_Mexico_men=heights_global[filter_Pais]
print(Height_Mexico_men)

[['139' 'Mexico' '170.29' '157.90' '5.59' '5.18']]